### ISSUE TITLE
下载数据集时报错 No such file or directory

### ISSUE THREAD

**Issue by Leon-377** [safe-graph/GNN-FakeNews#11]
你好，我在Google colab中使用pytorch_geometric执行到代码
`train_data = UPFD(root=".", name="gossipcop", feature="spacy", split="train")`
会报错 "FileNotFoundError: [Errno 2] No such file or directory: './gossipcop/raw/new_spacy_feature.npz'"

文件夹里有gossipcop/raw 的目录，但是其中没有文件
请问是出什么问题了？

**Comment by YingtongDou** [comment]
You need to download the data from this [link](https://drive.google.com/drive/folders/1OslTX91kLEYIi2WBnwuFtXsVz5SS_XeR?usp=sharing), upzip the data and put all files under the `./gossipcop/raw/`
