### ISSUE TITLE
the sequence length and word embedding dimension of word2vec embedding

### ISSUE THREAD

**Issue by shizia** [safe-graph/GNN-FakeNews#16]
Hello, I want to ask about what is the sequence length and word embedding dimension of spaCy word2vec embedding in your work?

**Comment by YingtongDou** [comment]
We use `en_core_web_lg` from spaCy to encode the text whose embedding dimension is **300**. Sequence with any length can be encoded by pretrained word2vec vectors.

**Comment by shizia** [comment]
> We use `en_core_web_lg` from spaCy to encode the text whose embedding dimension is **300**. Sequence with any length can be encoded by pretrained word2vec vectors.

Sorry for bothering again! 
I know that the final text embedding dimension is 300, but what I wonder is the dimension of each word. As a piece of text includes a sequence of words, whether the 300 is the sum of all words' dimension or each word is 300 dimension and some pooling way was used to make all 300-d words' embeddings become one final text embedding?
Thanks for your help!

**Comment by YingtongDou** [comment]
According to the [spaCy documentation](https://spacy.io/api/doc#vector), the sentence embedding is obtained by averaging all 300-d token (word) word2vec embeddings in the sentence.
