### ISSUE TITLE
raw data requirement

### ISSUE THREAD

**Issue by NonvolatileMemory** [safe-graph/GNN-FakeNews#18]
Hi,

Could you kindly release the raw data (original tweets) for that the crawler cannot crawl some tweet due to out of date or they have been deleted. It will be good to release the raw data.

**Comment by YingtongDou** [comment]
Thanks for your interest in our project. Due to Twitter's policy, we cannot share the raw data from Twitter. My suggestion is only to study news with the most accessible tweets or curate your own dataset using the latest fact-checking results from Politifact.

**Comment by NonvolatileMemory** [comment]
but with partial data cannot reproduce your result, can you email me (cnsdunm@gmail.com) the original data. For previous datasets like Twitter15 and 16, researchers can access the raw data if they send the email.
