### ISSUE TITLE
Profile Features for news do not match earliest tweet

### ISSUE THREAD

**Issue by rknntns** [safe-graph/GNN-FakeNews#19]
The new_profile_features include features for the news article the trees are based on. In a [closed issue](https://github.com/safe-graph/GNN-FakeNews/issues/14) it is stated, that "the first feature in each graph represents the news encoding plus the profile feature of the Twitter account who first tweets the news". 
So logically the profile feature of the first graph should be exactly the same as the profile feature for the account that tweets the news first, but it is equal to one of a later occurence in the graph.

What is the correct way to create the profile_features for the first features?

**Comment by YingtongDou** [comment]
You are correct. How many cases have you found where the first profile feature equals one of the later features in the same graph?

If there are only a few cases, those may indicate that the account that tweeted the source news retweeted the source news tweet later.
