### ISSUE TITLE
How to run UPFD？

### ISSUE THREAD

**Issue by a982847942** [safe-graph/GNN-FakeNews#20]
How can I run the model in the paper User Preference-aware Fake News Detection？

**Comment by a982847942** [comment]
sry , I already know.

**Comment by linlin0312** [comment]
> sry , I already know.

同学，你是已经复现出来了吗？方便请教几个问题吗？

**Comment by a982847942** [comment]
> > sry , I already know.
> 
> 同学，你是已经复现出来了吗？方便请教几个问题吗？



> > sry , I already know.
> 
> 同学，你是已经复现出来了吗？方便请教几个问题吗？

运行成功了，有什么问题说一下我看看，也不一定知道。

**Comment by linlin0312** [comment]
数据处理有些问题，想请问一下处理这个数据需要我们自己去使用推特API吗,processed文件里的数据是怎么得到的呀

**Comment by linlin0312** [comment]
> > > sry , I already know.
> > 
> > 
> > 同学，你是已经复现出来了吗？方便请教几个问题吗？
> 
> > > sry , I already know.
> > 
> > 
> > 同学，你是已经复现出来了吗？方便请教几个问题吗？
> 
> 运行成功了，有什么问题说一下我看看，也不一定知道。

数据处理有些问题，想请问一下处理这个数据需要我们自己去使用推特API吗,processed文件里的数据是怎么得到的呀

**Comment by TpBlair** [comment]
> > > sry , I already know.
> > 
> > 
> > 同学，你是已经复现出来了吗？方便请教几个问题吗？
> 
> > > sry , I already know.
> > 
> > 
> > 同学，你是已经复现出来了吗？方便请教几个问题吗？
> 
> 运行成功了，有什么问题说一下我看看，也不一定知道。
您这个数据集能否分享一下呢？

Brothers, since most of The data sets of rumor detection are not open, I have set up a group for everyone to share the data set. If you are interested, you can add me on wechat The-xyc or contact me by email [854070486@qq.com](mailto:854070486@qq.com). I will organize everyone.
