### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by muxiaofanNN** [safe-graph/GNN-FakeNews#23]
请问我从你这里下载的数据集是你论文的数据集嘛，我看不像呀

**Comment by ChaoPeng13** [comment]
When I ran the code from the codeocean.com, the results from online and local machine are very different. Could you please tell me the reason? Does the PyG version cause the difference?

**Comment by YingtongDou** [comment]
> When I ran the code from the codeocean.com, the results from online and local machine are very different. Could you please tell me the reason? Does the PyG version cause the difference?

Please install the corresponding PyG on codeocean.com on your local machine to see the if the performance aligns.

**Comment by YingtongDou** [comment]
> 请问我从你这里下载的数据集是你论文的数据集嘛，我看不像呀

The datasets are the same as the ones used in the papers

**Comment by muxiaofanNN** [comment]
您论文中不是有三个数据集嘛，twitter15 twitter16 MA2015 我这里就只能下载两个呀,然后的话是否可以给我呢，还有就是论文和代码我都认真的研读，就是数据集看不懂 每一个文件没有什么注释，比如A.txt 等 ，我已经认真看了一周呢，是否能够提供一下呢，谢谢呢

**Comment by muxiaofanNN** [comment]
还有就是嗯，您划分的数据集怎么是2：1：7 不太理解

**Comment by YingtongDou** [comment]
> 您论文中不是有三个数据集嘛，twitter15 twitter16 MA2015 我这里就只能下载两个呀,然后的话是否可以给我呢，还有就是论文和代码我都认真的研读，就是数据集看不懂 每一个文件没有什么注释，比如A.txt 等 ，我已经认真看了一周呢，是否能够提供一下呢，谢谢呢

This repo is for the [UPFD paper](https://arxiv.org/pdf/2104.12259.pdf); it does not use Twitter or MA2015 datasets. You may refer to the wrong paper.

**Comment by muxiaofanNN** [comment]
没错呢，我没懂那几个npz文件是干嘛的，就是new_bert_feature.npz，能不能解释下

**Comment by ChaoPeng13** [comment]
> > When I ran the code from the codeocean.com, the results from online and local machine are very different. Could you please tell me the reason? Does the PyG version cause the difference?
> 
> Please install the corresponding PyG on codeocean.com on your local machine to see the if the performance aligns.

Thanks! I guess the processed data causes the difference.

**Comment by Chenglu0426** [comment]
Could you tell me the corresponding order of the graphs and news ids in the graph data set?
