### ISSUE TITLE
How to map the new user profile features to the scales of the existing user profile feature?

### ISSUE THREAD

**Issue by panicpan2000** [safe-graph/GNN-FakeNews#26]
I tried to add some nodes and collected some profiles. Then, I tried to use profile_feature.py to generate 10-d feature.
However, the feature I obtained, such as [0, 0, 148, 222, 13,919, 12,829, 1, 89, 2], differs from the feature in the 'new_profile_feature.npz' file, which appears as [0, 0, 1.30814989e-04, 3.48118758e-03, 8.60901460e-03, 5.20881161e-03, 1.13039020e-03, 0.31065401, 0.14995132, 0.31599955].
How should I further process the features?
Thanks.

**Comment by YingtongDou** [comment]
I used the [MinMaxScaler](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html) from sklearn to scale the data from zero to one.
