### ISSUE TITLE
Bug Report in utils/eval_helper.py

### ISSUE THREAD

**Issue by Hazerank** [safe-graph/GNN-FakeNews#4]
There is a bug detected in the [utils/eval_helper.py](https://github.com/safe-graph/GNN-FakeNews/blob/018805d9e5701da33b66a9853b27e3899f594259/utils/eval_helper.py) file in the line 15. The problematic line is: 

`data_size = len(loader.dataset.indices)`

This raises an error while `.indices` is a function.

In order to fix this issue, the line should be updated as following:

 `data_size = len(loader.dataset.indices())`

**Comment by YingtongDou** [comment]
Fixed. Thanks!
