### ISSUE TITLE
SSLError occurred

### ISSUE THREAD

**Issue by shizia** [safe-graph/GNN-FakeNews#8]
When I run the code example of PyG, the SSLError occurred. `HTTPSConnectionPool(host='docs.google.com', port=443): Max retries exceeded with url: /uc?export=download&id=1KOmSrlGcC50PjkvRVbyb_WoWHVql06J- (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1125)')))` I have looked for solution online but still didn't slove it.  Do you know how to slove this problem ? Thanks!

**Comment by YingtongDou** [comment]
I think it's the error of the Google Drive downloader used by PyG, please make sure you can access Google Drive on your machine.

Alternatively, you can manually download the dataset from [Google Drive](https://drive.google.com/drive/folders/1OslTX91kLEYIi2WBnwuFtXsVz5SS_XeR?usp=sharing) or Baidu Disk: https://pan.baidu.com/s/1NFtuwzmpAezNcJzlSlduSw Password: fj43.

Please follow the instructions in repo readme to manually load the downloaded dataset.
